### ISSUE TITLE
Check this!

### ISSUE THREAD

**Issue by SadeghHayeri** [authq/captive-login#1]
https://github.com/SadeghHayeri/Mili

**Comment by pi0** [comment]
Great @SadeghHayeri :heart: I've added it to the related projects section. This script was mainly developed to be used in headless environments.

PS just discovered GreenTunnel! Really creative. I'm might be interested in contribution :)

**Comment by SadeghHayeri** [comment]
Thanks man! 💙
I hope it work for your ISP. PR welcome of course!
